version: '3'

services:
  srinu-springboot-container:
    image: srinu-spring-boot-docker-compose:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/srinu-springboot-container
    ports:
      - "8080-8100:8080"
