apiVersion: apps/v1
kind: Deployment
metadata:
  name: srinu-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: srinu-springboot
  template:
    metadata:
      labels:
        app: srinu-springboot
    spec:
      containers:
        - name: springboot
          image: 154349/srinu-docker-demo:srinu-docker-demo
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: srinu-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: srinu-springboot
